# Generated by Django 4.1.2 on 2022-10-25 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_song_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('song_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='artiste',
            old_name='content',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='artiste',
            old_name='song_id',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='artiste',
            name='age',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
